#!/usr/bin/env python3
"""
extract_dom_vector.py
─────────────────────
Extracts the straightforward spatial Difference of Means (DoM) 
concept vector from a given dataset tensor generated by the multi_extractor.

It operates strictly symmetrically and resolves to a stable 
linear shift axis shaped [512, 8, 8].
"""

import argparse
from pathlib import Path
import torch

def main():
    parser = argparse.ArgumentParser("Extract Difference of Means (DoM) Vector")
    parser.add_argument("--concept", type=str, required=True, help="Concept name (e.g. sharp_vs_blur)")
    parser.add_argument("--timestep", type=int, required=True, help="Specific timestep to extract the vector from.")
    args = parser.parse_args()
    
    input_file = Path("outputs") / f"{args.concept}.pt"
    if not input_file.exists():
        input_file = Path(args.concept)
        if not input_file.exists():
            print(f"Error: Could not locate data for '{args.concept}'.")
            return

    concept_name = input_file.stem
    data = torch.load(input_file, map_location="cpu")
    
    if args.timestep not in data["activations"]:
        print(f"Error: Timestep {args.timestep} not found. Available: {list(data['activations'].keys())}")
        return
        
    p_data = data["activations"][args.timestep]["plus"].float()
    m_data = data["activations"][args.timestep]["minus"].float()
    
    # 1) Standard Statistical Mean directly over nested structures yielding [512, 8, 8]
    mu_p = p_data.mean(dim=0)
    mu_m = m_data.mean(dim=0)
    
    # 2) Calculate Euclidean directional diff
    # NOTE: We do NOT unit-normalize. The raw magnitude carries the natural
    # activation-space scale of the concept. v_scale in the pipeline controls
    # the patch strength. Unit-normalizing a 32k-dim vector crushes each
    # element to ~0.005, making the patch invisible to the UNet.
    dom_vector = mu_p - mu_m
    
    out_dir = Path("vectors/doms")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{concept_name}.pt"
    
    torch.save(dom_vector.cpu(), out_path)
    print(f"\nSuccess! Extracted Difference of Means (DoM) Vector.")
    print(f"Final Tensor Shape: {tuple(dom_vector.shape)}")
    print(f"Saved directly to : {out_path}")

if __name__ == "__main__":
    main()
