#!/usr/bin/env python3
"""
train_linear_probe.py
─────────────────────
Trains a linear classifier on h-space concept representations.

For a provided concepts `.pt` tensor dict (generated by main_extractor.py),
this script steps through each diffusion timestep independently. For each timestep:

  1. Loads `plus` and `minus` variant tensors of shape [N, 512, 8, 8].
  2. Flattens them across all spatial components to [N, 32768].
  3. Prepares a train/test split natively linked against image index `N`
     (ensuring plus/minus variants from the same image stay clamped 
     in the same split, avoiding data leakage).
  4. Trains a PyTorch parallelized Linear Probe (nn.Linear) efficiently 
     on the GPU.
  5. Computes linear separability (test accuracy) exclusively.

Finally, plots the overall accuracy relative to the timesteps.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

def parse_args():
    parser = argparse.ArgumentParser("Linear Probe Trainer")
    parser.add_argument(
        "--file", type=str, required=True,
        help="Path to the .pt file (e.g. outputs/sharp_vs_blur.pt)"
    )
    parser.add_argument(
        "--epochs", type=int, default=150,
        help="Number of epochs for Full-Batch Gradient Descent (default: 150)"
    )
    parser.add_argument(
        "--lr", type=float, default=1e-3,
        help="Learning rate for AdamW (default: 1e-3)"
    )
    parser.add_argument(
        "--split_ratio", type=float, default=0.8,
        help="Percentage of image indices placed into the train set (default: 0.8)"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="RNG seed for consistent train/test splitting (default: 42)"
    )
    parser.add_argument(
        "--output_dir", type=str, default=None,
        help="Directory for plots/logs. Defaults to outputs/time-step-analysis"
    )
    parser.add_argument(
        "--timesteps", type=str, default="",
        help="Comma-separated timestep values to evaluate (default: all available)."
    )
    return parser.parse_args()


def parse_timesteps_arg(value: str) -> set[int] | None:
    if not value or not value.strip():
        return None
    return {int(x.strip()) for x in value.split(",") if x.strip()}


def train_probe_for_timestep(
    ts: int,
    plus_tensor: torch.Tensor,
    minus_tensor: torch.Tensor,
    device: torch.device,
    split_ratio: float,
    epochs: int,
    lr: float,
) -> float:
    """
    Trains a simple binary logistic regressor (nn.Linear) on the GPU
    using Full-Batch Gradient Descent and returns the final Test Accuracy.
    """
    n = min(plus_tensor.shape[0], minus_tensor.shape[0])
    if n < 2:
        raise ValueError("Need at least 2 samples per class after balancing.")

    plus_tensor = plus_tensor[:n]
    minus_tensor = minus_tensor[:n]

    N = n
    
    # 1) Flatten [N, 512, 8, 8] -> [N, 32768]
    p_flat = plus_tensor.flatten(start_dim=1).to(device, dtype=torch.float32)
    m_flat = minus_tensor.flatten(start_dim=1).to(device, dtype=torch.float32)
    feature_dim = p_flat.shape[1]

    # 2) Image-index safe train/test split
    indices = torch.randperm(N, device=device)
    n_train = int(N * split_ratio)
    
    train_idx = indices[:n_train]
    test_idx  = indices[n_train:]

    if n_train == 0 or len(test_idx) == 0:
        raise ValueError("Not enough samples to construct a train/test split. Increase num_samples.")

    X_train_plus  = p_flat[train_idx]
    X_train_minus = m_flat[train_idx]
    y_train_plus  = torch.ones((n_train,), device=device, dtype=torch.float32)
    y_train_minus = torch.zeros((n_train,), device=device, dtype=torch.float32)
    
    X_test_plus   = p_flat[test_idx]
    X_test_minus  = m_flat[test_idx]
    y_test_plus   = torch.ones((len(test_idx),), device=device, dtype=torch.float32)
    y_test_minus  = torch.zeros((len(test_idx),), device=device, dtype=torch.float32)

    # 3) Concatenate sets
    X_train = torch.cat([X_train_plus, X_train_minus], dim=0)
    y_train = torch.cat([y_train_plus, y_train_minus], dim=0)
    
    X_test = torch.cat([X_test_plus, X_test_minus], dim=0)
    y_test = torch.cat([y_test_plus, y_test_minus], dim=0)

    # Scramble train set arbitrarily so model doesn't just see all positives first
    shuf_idx = torch.randperm(len(y_train), device=device)
    X_train = X_train[shuf_idx]
    y_train = y_train[shuf_idx]

    # 4) Train
    model = nn.Linear(feature_dim, 1).to(device)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-2)
    
    model.train()
    for _ in range(epochs):
        optimizer.zero_grad()
        logits = model(X_train).squeeze()
        loss = F.binary_cross_entropy_with_logits(logits, y_train)
        loss.backward()
        optimizer.step()

    # 5) Test
    model.eval()
    with torch.no_grad():
        test_logits = model(X_test).squeeze()
        test_preds = (test_logits > 0.0).float()
        correct = (test_preds == y_test).sum().item()
        acc = correct / len(y_test)
        
    return acc


def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    selected_timesteps = parse_timesteps_arg(args.timesteps)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    pt_path = Path(args.file)
    concept_name = pt_path.stem
    
    base_dir = Path(__file__).resolve().parent.parent.parent
    out_dir = Path(args.output_dir) if args.output_dir else (base_dir / "outputs" / "time-step-analysis")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    log_file = out_dir / f"{concept_name}_separability_log.txt"
    logging.basicConfig(level=logging.INFO, format='%(message)s', handlers=[
        logging.FileHandler(log_file, mode='w'),
        logging.StreamHandler()
    ])
    logger = logging.getLogger()
    
    logger.info(f"={'=' * 60}")
    logger.info(f" Linear Probe Analysis")
    logger.info(f"={'=' * 60}")
    logger.info(f" Concept     : {concept_name}")
    logger.info(f" Data file   : {pt_path}")
    logger.info(f" Device      : {device}")
    logger.info(f" Split Ratio : {args.split_ratio}")
    logger.info(f" Epochs      : {args.epochs}")
    logger.info(f" LR          : {args.lr}")
    logger.info("-" * 61)

    if not pt_path.exists():
        logger.error(f"[!] Target file '{pt_path}' does not exist.")
        return

    data = torch.load(pt_path, map_location="cpu")
    activations = data["activations"]
    
    timesteps = sorted(activations.keys(), reverse=True) # Usually plotted with reverse timesteps (denoising step order)
    if selected_timesteps is not None:
        timesteps = [ts for ts in timesteps if ts in selected_timesteps]
    if not timesteps:
        logger.error("[!] No matching timesteps to evaluate.")
        return
    
    accuracies = []
    
    for ts in timesteps:
        plus_data = activations[ts]["plus"]
        minus_data = activations[ts]["minus"]
        
        acc = train_probe_for_timestep(
            ts=ts,
            plus_tensor=plus_data,
            minus_tensor=minus_data,
            device=device,
            split_ratio=args.split_ratio,
            epochs=args.epochs,
            lr=args.lr
        )
        accuracies.append(acc * 100.0)
        logger.info(f" TS: {ts:04d} | Shape: {tuple(plus_data.shape)} -> Flat: {plus_data.shape[1]*plus_data.shape[2]*plus_data.shape[3]} | Test Acc: {acc*100.0:>6.2f}%")

    # ---- Plotting ----
    plt.figure(figsize=(8, 5))
    plt.plot(timesteps, accuracies, marker="o", color="blue", linewidth=2)
    
    # Reverse X-axis to reflect Diffusion denoising process (T ... 0)
    plt.xlim(max(timesteps) + 50, min(timesteps) - 50)
    
    plt.title(f"Linear Separability: {concept_name}", fontsize=14, pad=10)
    plt.xlabel("Diffusion Timestep", fontsize=12)
    plt.ylabel("Test Accuracy (%)", fontsize=12)
    plt.ylim(0, 105)
    plt.grid(True, linestyle="--", alpha=0.6)

    out_plot_name = out_dir / f"{concept_name}_separability_plot.png"
    plt.savefig(out_plot_name, dpi=150, bbox_inches="tight")
    plt.close()
    
    logger.info("-" * 61)
    logger.info(f" Saved plot to : {out_plot_name}")
    logger.info(f"({'=' * 60})\n")

if __name__ == "__main__":
    main()
